version: "3.9"
services:
  redis:
    image: redis:7-alpine

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "5001:5001"
    depends_on:
      - redis

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api
